/* Tailwind config for the "Knight's Ledger" dark dashboard.
   Tokens are the canonical set from the Stitch mockups' shared tailwind.config
   (the dashboard file is source of truth; the abilities mockup drifted and is ignored).
   Content globs scan HTML + every JS render helper so string-built classes survive purge.
   Rule of thumb enforced in the render code: classes are always COMPLETE string literals
   (ternaries pick between full class strings); the only runtime-computed value
   (progress width / gauge angle) is emitted as an inline style, never as w-[N%]. */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#cbe6ff",
        "on-primary": "#00344f",
        "outline-variant": "#42474d",
        "surface-container-lowest": "#060e1b",
        "primary-fixed-dim": "#a0cbf0",
        "tertiary-container": "#005347",
        "success-green": "#16c60c",
        "danger-scarlet": "#f03a17",
        "surface-glow": "#10223b",
        "lichen-blue": "#aac7d4",
        "inverse-surface": "#dae3f4",
        "on-primary-container": "#92bde1",
        "surface-container-low": "#141c28",
        "surface-tint": "#a0cbf0",
        "border-bright": "#5e8dac",
        "tertiary": "#00dfc1",
        "secondary": "#ffdea3",
        "tertiary-fixed": "#00fedc",
        "primary": "#a0cbf0",
        "on-error": "#690005",
        "on-background": "#dae3f4",
        "surface": "#0a1424",
        "surface-container": "#18202d",
        "on-tertiary": "#00382f",
        "error-container": "#93000a",
        "on-primary-fixed": "#001e30",
        "on-surface": "#dae3f4",
        "outline": "#8c9198",
        "inverse-on-surface": "#28313e",
        "surface-variant": "#2d3543",
        "on-tertiary-fixed": "#00201a",
        "primary-container": "#1e4d6c",
        "on-secondary": "#412d00",
        "surface-container-high": "#222a37",
        "on-tertiary-container": "#00cfb3",
        "secondary-container": "#febb00",
        "tertiary-fixed-dim": "#00dfc1",
        "on-secondary-container": "#6b4d00",
        "secondary-fixed-dim": "#febb00",
        "inverse-primary": "#366283",
        "on-secondary-fixed-variant": "#5d4200",
        "on-secondary-fixed": "#261900",
        "border-dim": "#183c55",
        "surface-bright": "#313a47",
        "error": "#ffb4ab",
        "background": "#0b1420",
        "surface-container-highest": "#2d3543",
        "secondary-fixed": "#ffdea3",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#1b4b69",
        "on-surface-variant": "#c1c7ce",
        "on-tertiary-fixed-variant": "#005145",
        "surface-dim": "#0b1420",
        "faded-dream": "rgba(231, 251, 255, 0.6)",
      },
      borderRadius: {
        /* Override the small stone-cut radii but KEEP Tailwind's default
           rounded-full (9999px) so progress rings and the crest render as true circles
           (the mockup config's full:0.75rem was a bug that squared them off). */
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "unit": "4px",
        "section-gap": "48px",
        "container-max": "600px",
        "sidebar-width": "240px",
      },
      maxWidth: {
        "container-max": "600px",
        "sidebar-width": "240px",
      },
      fontFamily: {
        "display-lg": ["Cinzel", "serif"],
        "headline-md": ["Cinzel", "serif"],
        "headline-md-mobile": ["Cinzel", "serif"],
        "body-base": ["Heebo", "sans-serif"],
        "body-lg": ["Heebo", "sans-serif"],
        "body-bold": ["Heebo", "sans-serif"],
        "caption": ["Heebo", "sans-serif"],
        "label-sm": ["Heebo", "sans-serif"],
        "code-path": ["'Courier Prime'", "monospace"],
      },
      fontSize: {
        "display-lg": ["38px", { lineHeight: "48px", letterSpacing: "0.05em", fontWeight: "400" }],
        "headline-md": ["26px", { lineHeight: "34px", letterSpacing: "0.02em", fontWeight: "400" }],
        "headline-md-mobile": ["22px", { lineHeight: "28px", letterSpacing: "0.02em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "300" }],
        "body-bold": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "label-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "caption": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "code-path": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-sm-mobile": ["11px", { lineHeight: "14px", fontWeight: "400" }],
      },
      boxShadow: {
        "glow": "0 0 15px rgba(254, 187, 0, 0.3)",
        "glow-active": "0 0 20px rgba(254, 187, 0, 0.5)",
      },
    },
  },
  plugins: [],
};
